# Use root/example as user/password credentials
version: "3.1"

services:
    mongo:
        image: mongo
        container_name: mongodb_api
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./data/db:/data/db

volumes:
    dbdata:
        driver: local
